name: Build APK FIX 100%

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            build-essential \
            git zip unzip \
            openjdk-17-jdk \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev \
            wget curl

      - name: Setup Java 17 (WAJIB)
        run: |
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          java -version

      - name: Install Android SDK (FIXED)
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip

          mv cmdline-tools cmdline-tools/latest

          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | sdkmanager --licenses

          sdkmanager "platform-tools" \
                     "platforms;android-31" \
                     "build-tools;30.0.3"

      - name: Set environment
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDAPI=31" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Clean build
        run: buildozer android clean

      - name: Build APK
        run: buildozer android debug
